@NotificationServer_HostAddress = http://localhost:5283


POST  {{NotificationServer_HostAddress}}/api/Emails
Content-Type: Application/json
{
  "to": "shabnam.sadikhzada@gmail.com",
  "from": "ceyhunsa@code.edu.az",
  "bcc": "nazrinamai@code.edu.az",
  "cc": "eaupleah@gmail.com",
  "subject": "Ceyhunagayev",
  "body": "ceyhun",
  "attachments": []
}
